### ISSUE TITLE
failed to respond to the plugin6.(*GRPCProvider).ApplyResourceChange call

### ISSUE THREAD

**Issue by knandras** [larstobi/terraform-provider-multipass#15]
Hi!

I tried creating two Multipass instances, sadly the provider crashed. The instances are created in Multipass, but because of the crash, they are not written out to the state file, and on the next run, Terraform stops, because the instance names already exist in Multipass.

This is on MacOS Ventura 13.2, Terraform 1.3.9

---
[trace.log](https://github.com/larstobi/terraform-provider-multipass/files/10774717/trace.log)

╷
│ Error: Request cancelled
│
│ The plugin6.(*GRPCProvider).ValidateResourceConfig request was cancelled.
╵
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-multipass_v1.4.1 plugin:

panic: runtime error: index out of range [1] with length 1

goroutine 50 [running]:
github.com/larstobi/go-multipass/multipass.LaunchV2(0x140001aca40)
	github.com/larstobi/go-multipass@v1.2.0/multipass/launch.go:83 +0x6a0
terraform-provider-multipass/internal/provider.instanceResource.Create({{_, {_, _}}}, {_, _}, {{{{0x100e450a0, 0x1400050b6e0}, {0x100d7ef20, 0x1400050b020}}, {0x14000203620, ...}}, ...}, ...)
	terraform-provider-multipass/internal/provider/resource_instance.go:129 +0x2e0
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).CreateResource(0x140003585a0, {0x100e42398, 0x1400050aae0}, 0x140001ad360, 0x140001ad2a8)
	github.com/hashicorp/terraform-plugin-framework@v0.10.0/internal/fwserver/server_createresource.go:81 +0x3a0
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ApplyResourceChange(0x100e42398?, {0x100e42398, 0x1400050aae0}, 0x14000584ab0, 0x140001ad540)
	github.com/hashicorp/terraform-plugin-framework@v0.10.0/internal/fwserver/server_applyresourcechange.go:51 +0x408
github.com/hashicorp/terraform-plugin-framework/internal/proto6server.(*Server).ApplyResourceChange(0x140003585a0, {0x100e42398?, 0x1400050a990?}, 0x14000590320)
	github.com/hashicorp/terraform-plugin-framework@v0.10.0/internal/proto6server/server_applyresourcechange.go:52 +0x184
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ApplyResourceChange(0x140002a4500, {0x100e42398?, 0x1400050a180?}, 0x14000238070)
	github.com/hashicorp/terraform-plugin-go@v0.12.0/tfprotov6/tf6server/server.go:811 +0x370
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ApplyResourceChange_Handler({0x100e19e60?, 0x140002a4500}, {0x100e42398, 0x1400050a180}, 0x14000238000, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.12.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:385 +0x174
google.golang.org/grpc.(*Server).processUnaryRPC(0x1400029e1e0, {0x100e45200, 0x14000003380}, 0x140003cb200, 0x1400035bd70, 0x101215fe0, 0x0)
	google.golang.org/grpc@v1.48.0/server.go:1295 +0x9d8
google.golang.org/grpc.(*Server).handleStream(0x1400029e1e0, {0x100e45200, 0x14000003380}, 0x140003cb200, 0x0)
	google.golang.org/grpc@v1.48.0/server.go:1636 +0x840
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.48.0/server.go:932 +0x88
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.48.0/server.go:930 +0x298

Error: The terraform-provider-multipass_v1.4.1 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
[trace.log](https://github.com/larstobi/terraform-provider-multipass/files/10774710/trace.log)

**Comment by algo7** [comment]
Same situation on
```
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:        22.04
Codename:       jammy
multipass   1.11.0
multipassd  1.11.0
```
terraform code
```terraform

terraform {
  required_providers {
    multipass = {
      source  = "larstobi/multipass"
      version = "1.4.1"
    }
  }
}

resource "multipass_instance" "test" {
  name           = "test"
  image          = "22.04"
  cpus           = 1
  memory         = "1G"
  disk           = "5G"
}
```

**Comment by rcastley** [comment]
I am seeing a similar issue. Multipass v1.10.1 works just fine with the provider. As soon as I upgrade to v1.11.1 the issue happens

```
random_string.hostname: Creating...
random_string.hostname: Creation complete after 0s [id=rxqx]
data.template_file.user_data: Reading...
data.template_file.user_data: Read complete after 0s [id=17a3f3ce0a89efe2212b1e1cc1db76d71e109f2ed96fb754388cc5a57c94b149]
local_file.user_data: Creating...
local_file.user_data: Creation complete after 0s [id=6f4efbdd60a0c76814ad676b30a12ccdfb05917d]
multipass_instance.ubuntu: Creating...
multipass_instance.ubuntu: Still creating... [10s elapsed]
multipass_instance.ubuntu: Still creating... [20s elapsed]
multipass_instance.ubuntu: Still creating... [30s elapsed]
multipass_instance.ubuntu: Still creating... [40s elapsed]
multipass_instance.ubuntu: Still creating... [50s elapsed]
multipass_instance.ubuntu: Still creating... [1m0s elapsed]
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more
│ details.
╵

Stack trace from the terraform-provider-multipass_v1.4.1 plugin:

panic: runtime error: index out of range [1] with length 1

goroutine 5 [running]:
github.com/larstobi/go-multipass/multipass.LaunchV2(0xc000162a88)
	github.com/larstobi/go-multipass@v1.2.0/multipass/launch.go:83 +0x6b0
terraform-provider-multipass/internal/provider.instanceResource.Create({{_, {_, _}}}, {_, _}, {{{{0x17d3d50, 0xc000109b30}, {0x16173c0, 0xc0001093b0}}, {0xc0003bd770, ...}}, ...}, ...)
	terraform-provider-multipass/internal/provider/resource_instance.go:129 +0x370
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).CreateResource(0xc0002817a0, {0x17d0f80, 0xc000108f60}, 0xc000163390, 0xc0001632d8)
	github.com/hashicorp/terraform-plugin-framework@v0.10.0/internal/fwserver/server_createresource.go:81 +0x616
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ApplyResourceChange(0x17d0f80?, {0x17d0f80, 0xc000108f60}, 0xc00014ca20, 0xc000163570)
	github.com/hashicorp/terraform-plugin-framework@v0.10.0/internal/fwserver/server_applyresourcechange.go:51 +0x5ca
github.com/hashicorp/terraform-plugin-framework/internal/proto6server.(*Server).ApplyResourceChange(0xc0002817a0, {0x17d0f80?, 0xc000108e10?}, 0xc00013a2d0)
	github.com/hashicorp/terraform-plugin-framework@v0.10.0/internal/proto6server/server_applyresourcechange.go:52 +0x238
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ApplyResourceChange(0xc0000c12c0, {0x17d0f80?, 0xc000108600?}, 0xc000148070)
	github.com/hashicorp/terraform-plugin-go@v0.12.0/tfprotov6/tf6server/server.go:811 +0x4fc
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ApplyResourceChange_Handler({0x16b23e0?, 0xc0000c12c0}, {0x17d0f80, 0xc000108600}, 0xc000148000, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.12.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002ca1e0, {0x17d3eb0, 0xc00025e680}, 0xc000140000, 0xc000347ec0, 0x1bba080, 0x0)
	google.golang.org/grpc@v1.48.0/server.go:1295 +0xb0b
google.golang.org/grpc.(*Server).handleStream(0xc0002ca1e0, {0x17d3eb0, 0xc00025e680}, 0xc000140000, 0x0)
	google.golang.org/grpc@v1.48.0/server.go:1636 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.48.0/server.go:932 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.48.0/server.go:930 +0x28a

Error: The terraform-provider-multipass_v1.4.1 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by swareSPLUNK** [comment]
Same experience as rcastley

`random_string.hostname: Creating...
random_string.hostname: Creation complete after 0s [id=dapv]
data.template_file.user_data: Reading...
data.template_file.user_data: Read complete after 0s [id=731744200e3ed9190fad9723ae23a938358705041ce5c5c306025f8abd51edeb]
local_file.user_data: Creating...
local_file.user_data: Creation complete after 0s [id=e9e0c7827c752c379925018238f5d94a4a65094e]
multipass_instance.ubuntu: Creating...
multipass_instance.ubuntu: Still creating... [10s elapsed]
multipass_instance.ubuntu: Still creating... [20s elapsed]
multipass_instance.ubuntu: Still creating... [30s elapsed]
multipass_instance.ubuntu: Still creating... [40s elapsed]
multipass_instance.ubuntu: Still creating... [50s elapsed]
multipass_instance.ubuntu: Still creating... [1m0s elapsed]
multipass_instance.ubuntu: Still creating... [1m10s elapsed]
multipass_instance.ubuntu: Still creating... [1m20s elapsed]
multipass_instance.ubuntu: Still creating... [1m30s elapsed]
multipass_instance.ubuntu: Still creating... [1m40s elapsed]
multipass_instance.ubuntu: Still creating... [1m50s elapsed]
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin6.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain
│ more details.
╵

Stack trace from the terraform-provider-multipass_v1.4.1 plugin:

panic: runtime error: index out of range [1] with length 1

goroutine 11 [running]:
github.com/larstobi/go-multipass/multipass.LaunchV2(0xc0004cca88)
	github.com/larstobi/go-multipass@v1.2.0/multipass/launch.go:83 +0x6b0
terraform-provider-multipass/internal/provider.instanceResource.Create({{_, {_, _}}}, {_, _}, {{{{0x17d3d50, 0xc00033e4b0}, {0x16173c0, 0xc0002022d0}}, {0xc00040f8c0, ...}}, ...}, ...)
	terraform-provider-multipass/internal/provider/resource_instance.go:129 +0x370
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).CreateResource(0xc000263d40, {0x17d0f80, 0xc00078bb90}, 0xc0004cd390, 0xc0004cd2d8)
	github.com/hashicorp/terraform-plugin-framework@v0.10.0/internal/fwserver/server_createresource.go:81 +0x616
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ApplyResourceChange(0x17d0f80?, {0x17d0f80, 0xc00078bb90}, 0xc0002a4510, 0xc0004cd570)
	github.com/hashicorp/terraform-plugin-framework@v0.10.0/internal/fwserver/server_applyresourcechange.go:51 +0x5ca
github.com/hashicorp/terraform-plugin-framework/internal/proto6server.(*Server).ApplyResourceChange(0xc000263d40, {0x17d0f80?, 0xc00078ba40?}, 0xc00013b220)
	github.com/hashicorp/terraform-plugin-framework@v0.10.0/internal/proto6server/server_applyresourcechange.go:52 +0x238
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ApplyResourceChange(0xc000223220, {0x17d0f80?, 0xc00078b260?}, 0xc00014a230)
	github.com/hashicorp/terraform-plugin-go@v0.12.0/tfprotov6/tf6server/server.go:811 +0x4fc
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ApplyResourceChange_Handler({0x16b23e0?, 0xc000223220}, {0x17d0f80, 0xc00078b260}, 0xc00014a1c0, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.12.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002aa1e0, {0x17d3eb0, 0xc0001024e0}, 0xc000795e60, 0xc00033ffb0, 0x1bba080, 0x0)
	google.golang.org/grpc@v1.48.0/server.go:1295 +0xb0b
google.golang.org/grpc.(*Server).handleStream(0xc0002aa1e0, {0x17d3eb0, 0xc0001024e0}, 0xc000795e60, 0x0)
	google.golang.org/grpc@v1.48.0/server.go:1636 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.48.0/server.go:932 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.48.0/server.go:930 +0x28a

Error: The terraform-provider-multipass_v1.4.1 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.`

**Comment by algo7** [comment]
Any news?

**Comment by lobotgn** [comment]
The same issue ...

**Comment by hugomf** [comment]
the problem happens when you specified the memory value (at least for me), if you don't specify memory, it is working fine

**Comment by rcastley** [comment]
@hugomf Nice find ... shame the default memory is only 1Gb :-(

Are you going to do a PR on that, if not then I can and then hopefully a new provider can be released @larstobi ?

Thank you :-)

**Comment by larstobi** [comment]
Thanks for the find, hugomf! PRs always welcome, but I can also try to implement your fix.

**Comment by hugomf** [comment]
I’m more than happy to help and send you a PR however I would need some guidance on how to get it fully tested from the terraform provider, so far I could reproduce the error by just running the golang code in the other repo and also how I  need to ensure that this change will work with multipass previous versions?, I reviewed multipass source code and they made this memory option flag change from version v1.11.0-rc

**Comment by hugomf** [comment]
@larstobi, @rcastley   Please review my pull request. Your feedback would be highly appreciated.

**Comment by larstobi** [comment]
Thanks, @hugomf ! This should be fixed by larstobi/go-multipass/pull/8 and #19 

It works on my machine. Can somebody else test it too?

**Comment by larstobi** [comment]
[v1.4.2-beta](https://github.com/larstobi/terraform-provider-multipass/releases/tag/v1.4.2-beta)

**Comment by larstobi** [comment]
@rcastley @knandras Would you like to test it too?

**Comment by rcastley** [comment]
@larstobi Do you have any docs on how to test the beta version locally please? Also multipass 1.12.0 is out the with 1.4.1 the issue persists.

**Comment by rcastley** [comment]
Or could you publish it as a Terraform beta provider over at https://registry.terraform.io/providers/larstobi/multipass/latest?

**Comment by rcastley** [comment]
Figured it out :-)

`~/.terraformrc`

```
provider_installation {
  dev_overrides {
    "larstobi/multipass" = "/Users/rwc/Downloads/terraform-provider-multipass-1.4.2-beta"
  }
  direct {}
}
```

**Comment by rcastley** [comment]
And it works perfectly again with Multipass 1.12.0 :-)

```
random_string.hostname: Creating...
random_string.hostname: Creation complete after 0s [id=pvhr]
local_file.user_data: Creating...
local_file.user_data: Creation complete after 0s [id=f64e2e40b78d8889bc9052a66510c7040a83aa0f]
multipass_instance.ubuntu: Creating...
multipass_instance.ubuntu: Still creating... [10s elapsed]
multipass_instance.ubuntu: Still creating... [20s elapsed]
multipass_instance.ubuntu: Still creating... [30s elapsed]
multipass_instance.ubuntu: Still creating... [40s elapsed]
multipass_instance.ubuntu: Still creating... [50s elapsed]
multipass_instance.ubuntu: Still creating... [1m0s elapsed]
multipass_instance.ubuntu: Still creating... [1m10s elapsed]
multipass_instance.ubuntu: Still creating... [1m20s elapsed]
multipass_instance.ubuntu: Still creating... [1m30s elapsed]
multipass_instance.ubuntu: Still creating... [1m40s elapsed]
multipass_instance.ubuntu: Still creating... [1m50s elapsed]
multipass_instance.ubuntu: Creation complete after 1m58s [name=pvhr]
data.multipass_instance.ubuntu: Reading...
data.multipass_instance.ubuntu: Read complete after 1s [name=pvhr]

Apply complete! Resources: 3 added, 0 changed, 0 destroyed.

Outputs:

instance_details = [
  {
    "image" = "Ubuntu 22.04.2 LTS"
    "image_hash" = "604837370399 (Ubuntu 22.04 LTS)"
    "ipv4" = "192.168.205.205"
    "name" = "pvhr"
    "state" = "Running"
  },
]
```

**Comment by larstobi** [comment]
Nice! And I published binaries for the beta provider now.

**Comment by larstobi** [comment]
Released as https://github.com/larstobi/terraform-provider-multipass/releases/tag/v1.4.2

**Comment by rcastley** [comment]
Just to confirm the full cycle ... destroy works as well 👍🏻 

```
multipass_instance.ubuntu: Destroying... [name=pvhr]
multipass_instance.ubuntu: Still destroying... [name=pvhr, 10s elapsed]
multipass_instance.ubuntu: Still destroying... [name=pvhr, 20s elapsed]
multipass_instance.ubuntu: Still destroying... [name=pvhr, 30s elapsed]
multipass_instance.ubuntu: Still destroying... [name=pvhr, 40s elapsed]
multipass_instance.ubuntu: Still destroying... [name=pvhr, 50s elapsed]
multipass_instance.ubuntu: Still destroying... [name=pvhr, 1m0s elapsed]
multipass_instance.ubuntu: Still destroying... [name=pvhr, 1m10s elapsed]
multipass_instance.ubuntu: Still destroying... [name=pvhr, 1m20s elapsed]
multipass_instance.ubuntu: Still destroying... [name=pvhr, 1m30s elapsed]
multipass_instance.ubuntu: Destruction complete after 1m31s
local_file.user_data: Destroying... [id=f64e2e40b78d8889bc9052a66510c7040a83aa0f]
local_file.user_data: Destruction complete after 0s
random_string.hostname: Destroying... [id=pvhr]
random_string.hostname: Destruction complete after 0s

Destroy complete! Resources: 3 destroyed.
```

**Comment by larstobi** [comment]
Thanks, @rcastley !

**Comment by rcastley** [comment]
w00t!

```
Initializing the backend...

Initializing provider plugins...
- Finding latest version of hashicorp/random...
- Finding latest version of hashicorp/local...
- Finding larstobi/multipass versions matching "~> 1.4.1"...
- Using previously-installed hashicorp/random v3.5.1
- Using previously-installed hashicorp/local v2.4.0
- Installing larstobi/multipass v1.4.2...
- Installed larstobi/multipass v1.4.2 (self-signed, key ID 797707331BF3549C)
```

**Comment by larstobi** [comment]
Hmm, does this look like the error is from multipass, and not from this provider?
